# Generated by Django 3.1.1 on 2020-11-13 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0029_sedeempleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('clave', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.IntegerField()),
                ('is_seration', models.BooleanField(default=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('rvoe', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('modular', models.IntegerField()),
                ('ano', models.CharField(max_length=4)),
                ('duracion', models.SmallIntegerField(max_length=6)),
                ('num_creditos', models.SmallIntegerField(max_length=6)),
                ('num_materias', models.SmallIntegerField(max_length=6)),
                ('num_parciales', models.IntegerField()),
                ('num_extras', models.IntegerField()),
                ('max_extras', models.IntegerField()),
                ('max_faltas', models.IntegerField()),
                ('max_dms_promedio', models.IntegerField()),
                ('max_dms', models.IntegerField()),
                ('carrera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.carrera')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanMateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('clave', models.CharField(max_length=20)),
                ('semestre', models.IntegerField()),
                ('horas_docente', models.IntegerField()),
                ('horas_independientes', models.IntegerField()),
                ('horas_campo', models.IntegerField()),
                ('creditos', models.IntegerField()),
                ('parent_at', models.IntegerField()),
                ('eje_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.eje')),
                ('materia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.materia')),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.plan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
